# Generated by Django 2.0.3 on 2018-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0002_auto_20180317_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='career',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
