# Generated by Django 2.0.3 on 2018-03-30 13:30

from django.db import migrations, models
import supervise.models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0003_auto_20180322_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='headImg',
            field=models.ImageField(default=None, upload_to=supervise.models.upload_to),
            preserve_default=False,
        ),
    ]
