# Generated by Django 2.0.3 on 2018-03-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0004_auto_20180330_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='headImg',
            new_name='avatar',
        ),
    ]
