# Generated by Django 2.0.3 on 2018-04-12 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0005_auto_20180330_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='last_login_ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='last_login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 19, 2, 47, 491567)),
        ),
    ]
