# Generated by Django 2.0.3 on 2018-03-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exName', models.CharField(max_length=10)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('validate', models.BooleanField(default=True)),
                ('file', models.FileField(default=None, upload_to='files')),
                ('path', models.FilePathField()),
            ],
        ),
    ]
