# Generated by Django 2.0.3 on 2018-03-29 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='issue_time',
            new_name='generate_time',
        ),
        migrations.AddField(
            model_name='model',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='files.ManagedFile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texture',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='files.ManagedFile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texture',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texture',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='browseNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='files.ManagedFile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
