# Generated by Django 2.0.3 on 2018-03-30 14:09

import design.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20180329_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='file',
            field=models.FileField(upload_to=design.models.upload_to),
        ),
        migrations.AlterField(
            model_name='texture',
            name='file',
            field=models.FileField(upload_to=design.models.upload_to),
        ),
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(upload_to=design.models.upload_to),
        ),
    ]
