# Generated by Django 2.0.3 on 2018-04-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_indoortype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('extension', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='furnitureType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='design.FurnitureType'),
        ),
        migrations.AddField(
            model_name='model',
            name='modelType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='design.ModelType'),
        ),
    ]
