# Generated by Django 2.0.3 on 2018-04-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_furnituretype_modeltype_scenetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='furnitureType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='design.FurnitureType'),
        ),
        migrations.AddField(
            model_name='model',
            name='modelType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='design.ModelType'),
        ),
        migrations.AddField(
            model_name='work',
            name='sceneType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='design.SceneType'),
        ),
    ]
